default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres
  username: postgres.hkryskhjtlaamwnheylv
  password: FAnantenna16!
  host: aws-0-ap-southeast-1.pooler.supabase.com
  port: 6543
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false


test:
  <<: *default
  database: app_test
  username: postgres
  password: your_local_password
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false

